# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import numpy as np

def generate_synthetic_data(n_samples=1000):
    np.random.seed(42)
    days = np.arange(n_samples)
    pressure = np.random.normal(3000, 200, n_samples)
    flow_rate = np.random.normal(200, 50, n_samples)
    water_cut = np.random.uniform(0.1, 0.4, n_samples)

    production_rate = 1000 + 0.8 * pressure + 1.2 * flow_rate - 150 * water_cut + np.random.normal(0, 50, n_samples)

    df = pd.DataFrame({
        'day': days,
        'pressure': pressure,
        'flow_rate': flow_rate,
        'water_cut': water_cut,
        'production_rate': production_rate
    })

    df.to_csv('raw_data.csv', index=False)
    print("✅ Synthetic data saved as raw_data.csv")

if __name__ == "__main__":
    generate_synthetic_data()